#!/bin/bash

[[ $_ != $0 ]] && echo "Script is being sourced... exiting" && return || echo "Script is a subshell... continuing"

PROGNAME=$0
PWD=$(pwd)
SCRIPT_DIR=$(realpath $(dirname $0))
ROOT_DIR=$(realpath $SCRIPT_DIR/..)

echo "PROGNAME   = $PROGNAME"
echo "PWD        = $PWD"
echo "SCRIPT_DIR = $SCRIPT_DIR"
echo "ROOT_DIR   = $ROOT_DIR"

trap 'cd $PWD' EXIT ERR INT TERM

usage() {
  cat << EOF >&2
Usage: $PROGNAME [-v] [-r<realm>] [-e<environment>]

      -r <realm>: ...
-e <environment>: ...
              -v: ...
EOF
  exit 1
}

#dir=default_dir file=default_file verbose_level=0
while getopts r:e:v o; do
  case $o in
    (r) realm=$OPTARG;;
    (e) environment=$OPTARG;;
    (v) verbose_level=$((verbose_level + 1));;
    (*) usage
  esac
done
shift "$((OPTIND - 1))"

echo Remaining arguments: "$@"

cd $SCRIPT_DIR/..

tfapply_realm_components() {
  echo "Started running \"tfapply\" against all components in realm \"$1\""

  while read component
  do
      echo $component
      if [ ! -z "$component" ]
      then
  	  tfapply_realm_component $1 $component
      fi
  done < $SCRIPT_DIR/config/realm.$1.cfg

    
  echo "Finished running \"tfapply\" against all components in realm \"$1\""
}

tfapply_realm_component() {
  echo "Started running \"tfapply\" against \"$2\" component in realm \"$1\""

  cd "$ROOT_DIR/realms/$1/components/$2/"
  echo "Directory changed to \"$(pwd)\""
  tfinit
  tfapply -auto-approve
    
  echo "Finished running \"tfapply\" against \"$2\" component in realm \"$1\""
}

tfapply_environment_components() {
  echo "Started running \"tfapply\" against all components in realm \"$1\" / environment \"$2\""

  while read component
  do
      echo $component
      if [ ! -z "$component" ]
      then
  	  tfapply_environment_component $1 $2 $component
      fi
  done < $SCRIPT_DIR/config/environment.$2.cfg

    
  echo "Finished running \"tfapply\" against all components in realm \"$1\" / environment \"$2\""
}

tfapply_environment_component() {
  echo "Started running \"tfapply\" against \"$3\" component in realm \"$1\" / environment \"$2\""

  cd "$ROOT_DIR/realms/$1/environments/$2/$3"
  echo "Directory changed to \"$(pwd)\""
  tfinit
  tfapply -auto-approve
    
  echo "Finished running \"tfapply\" against \"$3\" component in realm \"$1\" / environment \"$2\""
}

if [ -n $realm ]; then tfapply_realm_components $realm; fi
if [ -n $environment ]; then tfapply_environment_components $realm $environment; fi
