#!/bin/bash

regexp="terraform/realms/(.*)/environments/(.*)/.*"

after() {
    echo "Removing decrypted files..."
    rm $1/*.backend.config
}

trap 'after $config_location' EXIT ERR INT TERM

if [[ $PWD =~ $regexp ]]
then
	environment="${BASH_REMATCH[2]}"
	echo "environment = $environment"

	config_location="../../../../../config"

	echo "Creating decrypted files..."
    ansible-vault decrypt "$config_location/environment.$environment.backend.config.vault" --output "$config_location/environment.$environment.backend.config" --vault-password-file $config_location/vault.password

	terraform init -backend-config $config_location/environment.$environment.backend.config
else
	regexp="terraform/realms/(.*)/components/.+"
	
	if [[ $PWD =~ $regexp ]]
	then
		realm="${BASH_REMATCH[1]}"
		echo "realm = ${realm}"

		config_location="../../../../config"

	    echo "Creating decrypted files..."
	    ansible-vault decrypt "$config_location/realm.$realm.backend.config.vault" --output "$config_location/realm.$realm.backend.config" --vault-password-file $config_location/vault.password

		terraform init -backend-config $config_location/realm.$realm.backend.config
	fi
fi

echo "realm = ${realm}"
echo "environment = $environment"




