apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          emptyDir: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: 'nginx'
    kubernetes.io/tls-acme: 'true'
  labels:
    app.kubernetes.io/name: nexus-server
  name: nexus-server
spec:
  rules:
    - host: nexus.sapienceanalytics.com
      http:
        paths:
          - backend:
              serviceName: nexus-service
              servicePort: 8081
            path: /
  tls:
    - hosts:
        - nexus.sapienceanalytics.com
      secretName: nexus-server-certs