apiVersion: v1
kind: PersistentVolume
metadata:
  name: tomcat-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: tomcat-server
  template:
    metadata:
      labels:
        app: tomcat-server
    spec:
      containers:
        - name: tomcat
          image: tomcat:8.0
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tomcat-pv-storage
              mountPath: /tomcat-data
      volumes:
        - name: tomcat-pv-storage
          persistentVolumeClaim:
            claimName: tomcat-pv-claim
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: 'nginx'
    kubernetes.io/tls-acme: 'true'
  labels:
    app.kubernetes.io/name: tomcat-server
  name: tomcat-server
spec:
  rules:
    - host: tomcat.sapienceanalytics.com
      http:
        paths:
          - backend:
              serviceName: tomcat-service
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - tomcat.sapienceanalytics.com
      secretName: tomcat-server-certs