#!/bin/bash

regexp="terraform/realms/(.*)/environments/(.*)/.*"

if [[ $PWD =~ $regexp ]]
then
	realm="${BASH_REMATCH[1]}"
	environment="${BASH_REMATCH[2]}"
	echo "realm = ${realm}"
	echo "environment = $environment"
	terraform apply -var-file ../../../../../config/realm.$realm.tfvars -var-file ../../../../../config/environment.$environment.tfvars
else
	regexp="terraform/realms/(.*)/components/.+"
	
	if [[ $PWD =~ $regexp ]]
	then
		realm="${BASH_REMATCH[1]}"
		echo "realm = ${realm}"
		terraform apply -var-file ../../../../config/realm.$realm.tfvars
	fi
fi

echo "realm = ${realm}"
echo "environment = $environment"




