#!/bin/bash

regexp="terraform/realms/(.*)/environments/(.*)/.*"

before() {
    echo "Creating decrypted files..."

    ansible-vault decrypt "$1/backend.config.vault" --output "$1/backend.config" --vault-password-file $1/vault.password
}

after() {
    echo "Removing decrypted files..."
    
    rm -f "$1/backend.config"
}

trap 'after $config_location' EXIT ERR INT TERM

if [[ $PWD =~ $regexp ]]
then
	realm="${BASH_REMATCH[1]}"
	environment="${BASH_REMATCH[2]}"
	echo "realm = ${realm}"
	echo "environment = $environment"

	config_location="../../../../../config"

	before $config_location
	
	terraform init -backend-config $config_location/backend.config
else
	regexp="terraform/realms/(.*)/components/.+"
	
	if [[ $PWD =~ $regexp ]]
	then
		realm="${BASH_REMATCH[1]}"
		echo "realm = ${realm}"

		config_location="../../../../config"

		before $config_location
	
		terraform init -backend-config $config_location/backend.config
	fi
fi

echo "realm = ${realm}"
echo "environment = $environment"




