#!/bin/bash

regexp="terraform/realms/(.*)/environments/(.*)/.*"

if [[ $PWD =~ $regexp ]]
then
	realm="${BASH_REMATCH[1]}"
	environment="${BASH_REMATCH[2]}"
	echo "realm = ${realm}"
	echo "environment = $environment"
	terraform init -backend-config ../../../../../config/backend.config
else
	regexp="terraform/realms/(.*)/components/.+"
	
	if [[ $PWD =~ $regexp ]]
	then
		realm="${BASH_REMATCH[1]}"
		echo "realm = ${realm}"
		terraform init -backend-config ../../../../config/backend.config
	fi
fi

echo "realm = ${realm}"
echo "environment = $environment"




