#!/bin/bash

regexp="terraform/realms/(.*)/environments/(.*)/.*"

before() {
    echo "Creating decrypted files..."

	# $2 = realm
	tfvarsrealm=`echo $2 | sed -E 's/-(black)//g'`
	echo $tfvarsrealm
    ansible-vault decrypt "$1/realm.$tfvarsrealm.tfvars.vault" --output "$1/realm.$tfvarsrealm.tfvars" --vault-password-file $1/$tfvarsrealm.vault.password

	# $3 = environment
	if [ $# -gt 2 ]
		then
			ansible-vault decrypt "$1/realm.$tfvarsrealm.environment.$3.tfvars.vault" --output "$1/realm.$tfvarsrealm.environment.$3.tfvars" --vault-password-file $1/$tfvarsrealm.vault.password
	fi
}

after() {
    echo "Removing decrypted files..."
    
	# $tfvarsrealm = realm
    rm -f "$1/realm.$tfvarsrealm.tfvars"

	# $3 = environment
	if [ $# -gt 2 ]
		then
			rm -f "$1/realm.$tfvarsrealm.environment.$3.tfvars"
	fi
}

trap 'after $config_location $realm $environment' EXIT ERR INT TERM

if [[ $PWD =~ $regexp ]]
then
	realm="${BASH_REMATCH[1]}"
	tfvarsrealm=`echo $2 | sed -E 's/-(black)//g'`
	environment="${BASH_REMATCH[2]}"
	echo "realm = ${realm}"
	echo "environment = $environment"

	config_location="../../../../../config"

	before $config_location $realm $environment
	
	terraform $1 -var-file $config_location/realm.$tfvarsrealm.tfvars -var-file $config_location/realm.$tfvarsrealm.environment.$environment.tfvars "${@:2}"
else
	regexp="terraform/realms/(.*)/components/.+"
	
	if [[ $PWD =~ $regexp ]]
	then
		realm="${BASH_REMATCH[1]}"
		tfvarsrealm=`echo $2 | sed -E 's/-(black)//g'`
		echo "realm = ${realm}"

		config_location="../../../../config"

		before $config_location $realm
	
		terraform $1 -var-file $config_location/realm.$tfvarsrealm.tfvars "${@:2}"
	fi
fi

echo "realm = ${realm}"
echo "environment = $environment"




