apiVersion: v1
kind: Pod
metadata:
  name: stress-500m-1
spec:
  containers:
  - name: stress-500m
    image: vish/stress
    resources:
      limits:
        cpu: "500m"
      requests:
        cpu: "500m"
    args:
    - -cpus
    - "2"
